### ISSUE TITLE
SendToReplicas Option Issue in Cluster Mode

### ISSUE THREAD

**Issue by moment1027** [valkey-io/valkey-go#11]
In cluster mode, regardless of SendToReplica and ReplicaOnly option value settings
When calling keys(), the slave node does not return data.
However, when calling scan(), the data is returned from the slave node as shown in the results below.

// SetTest
[Set] key:key_0, value:value_0
[Set] key:key_1, value:value_1
[Set] key:key_2, value:value_2
[Set] key:key_3, value:value_3
[Set] key:key_4, value:value_4
 
// KeysTest
[Keys] address:172.18.0.3:6379, keys:[key_3]				// master
[Keys] address:172.18.0.5:6379, keys:[key_2]				// master
[Keys] address:172.18.0.6:6379, keys:[key_4 key_1 key_0]	// master	
[Keys] address:172.18.0.2:6379, keys:[]					// slave
[Keys] address:172.18.0.7:6379, keys:[]					// slave
[Keys] address:172.18.0.4:6379, keys:[]					// slave
 
// ScanTest
[Scan] address:172.18.0.3:6379, keys:[key_3]				// master
[Scan] address:172.18.0.5:6379, keys:[key_2]				// master
[Scan] address:172.18.0.6:6379, keys:[key_4 key_0 key_1]	// master
[Scan] address:172.18.0.2:6379, keys:[key_3]				// slave
[Scan] address:172.18.0.7:6379, keys:[key_2]				// slave
[Scan] address:172.18.0.4:6379, keys:[key_0 key_4 key_1]	// slave

The client generation code for obtaining data only from the master node is as follows.

```
clusterClient, err := valkey.NewClient(valkey.ClientOption{
        InitAddress: conf.Addr,
        Password:    conf.Password,
        SelectDB:    conf.DB,
        SendToReplicas: func(cmd valkey.Completed) bool {
            return false
        },
        ReplicaOnly: false,
})
```

**Comment by rueian** [comment]
Hi @moment1027,

I could not reproduce your situation. My KeysTest showed the same result as the ScanTest. Could it be possibly caused by replication lag on your server?

**Comment by rueian** [comment]
Staled
