### ISSUE TITLE
[Question] Ping function

### ISSUE THREAD

**Issue by weslenng** [valkey-io/valkey-go#14]
How can I ping a Valkey server just to know if he is alive and healthy?
I feel functions like that are extremely useful when you're dealing with microservices and a lot of DBs (especially at the service startup)

**Comment by gotama** [comment]
There is a PING command that responds with PONG.

**Comment by rueian** [comment]
You can do PING with valkey-go by:

```go
package main

import (
	"context"
	"github.com/valkey-io/valkey-go"
)

func main() {
	client, err := valkey.NewClient(valkey.ClientOption{InitAddress: []string{"127.0.0.1:6379"}})
	if err != nil {
		panic(err)
	}
	err = client.Do(context.Background(), client.B().Ping().Build()).Error()
}
```

However, you usually don't need to do that. If the `err` return by `valkey.NewClient` is nil, the server is guaranteed to be alive.
