### ISSUE TITLE
[Question] Create Zadd

### ISSUE THREAD

**Issue by AntonioMaccarini** [valkey-io/valkey-go#15]
Hello, I couldn’t find an example of how to create a ZADD command. Based on my understanding of the library, I thought it would work like this, but I’m unable to make it function. Could you provide some guidance or a working example?

When I follow the process step by step, the only option I see at first is the Key:

![{27F8D10B-0BA7-4FD7-B92B-91C0A0FF998E}](https://github.com/user-attachments/assets/b0764c14-2904-45a2-b98d-8dc40848821f)

Afterward, I can select from the options listed below, but I haven't been able to get it to work.
![{716391F5-EB83-4378-B8EC-B0DBC7DA2641}](https://github.com/user-attachments/assets/6ce8fadf-7900-428e-81e7-c2a28a4a9e37)

Thanks in advance for your help.

**Comment by rueian** [comment]
Hi @AntonioMaccarini, here is an example:

```go
func main() {
	client, err := valkey.NewClient(valkey.ClientOption{
		InitAddress: []string{"127.0.0.1:6379"},
	})
	if err != nil {
		panic(err)
	}
	cmd := client.B().Zadd().Key("myset").ScoreMember()
	for i := range 10 {
		cmd.ScoreMember(float64(i), strconv.Itoa(i))
	}
	if err = client.Do(context.Background(), cmd.Build()).Error(); err != nil {
		panic(err)
	}
	fmt.Println(client.Do(context.Background(), client.B().Zrange().Key("myset").Min("0").Max("-1").Withscores().Build()).AsZScores())
}
```

**Comment by AntonioMaccarini** [comment]
Thanks @rueian!
