### ISSUE TITLE
go get package failed

### ISSUE THREAD

**Issue by Dmarcotrigiano** [valkey-io/valkey-go#2]
Using Go Nightly VsCode extension `v2024.4.2318` on Ubuntu

```
Command 'gopls.go_get_package' failed: 

Error: 
err: exit status 1: stderr: github.com/valkey-io/valkey-go@v1.0.35: 

parsing go.mod: 
module declares its path as: 
github.com/rueian/valkey-go but was required as: github.com/valkey-io/valkey-go .
```

**Comment by ymmt2005** [comment]
The tag v1.0.35 was re-created, so I guess the first tagged version was cached in [proxy.golang.org](https://proxy.golang.org/).

The easiest fix would be to cut another release, I guess.

**Comment by rueian** [comment]
Hi @Dmarcotrigiano, @ymmt2005

The v1.0.35 tag was released before we moved this repo to valkey-io from my personal account.

Therefore I just prepared another tag. Please use `go get github.com/valkey-io/valkey-go@v1.0.35-io` instead.

**Comment by rueian** [comment]
We can close this issue now because v1.0.36 was released.
